name: Bug Report (English)
description: Report a bug to help us improve Salience-DETR.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting an issue, please consider starring our project ⭐. Your encouragement is our motivation for maintenance!

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        Paste environment information from the beginning of console output, i.e.:
        ```
        sys.platform linux
        Python 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:21:28) [GCC 12.3.0]
        numpy 1.24.4
        PyTorch 1.12.1+cu113 @/home/ubuntu22/anaconda3/envs/sl/lib/python3.8/site-packages/torch
        PyTorch debug build False
        torch._C._GLIBCXX_USE_CXX11_ABI False
        GPU available Yes
        GPU 0 NVIDIA GeForce RTX 3090 (arch=8.6)
        Driver version 546.17
        CUDA_HOME /usr/local/cuda-11.3
        Pillow 10.3.0
        torchvision 0.13.1+cu113 @/home/ubuntu22/anaconda3/envs/sl/lib/python3.8/site-packages/torchvision
        torchvision arch flags 3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
        fvcore 0.1.5.post20221221
        iopath 0.1.9
        cv2 4.9.0
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
